version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
      env_file:
        - ./.env
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=${USER}
        - POSTGRES_PASSWORD=${PASSWORD}
        - POSTGRES_DB=${NAME}
      ports:
        - 5432:5432
volumes:
  postgres_data: